MAP_DATA = {
    (1, 1): [
        "                                                                                                                                   F ",
        "   T              T                      T                    T                      T                                          |          ",
        "                                                                                                                                   | ",
        "            QBQBQBQ                     BBBBBBBBB                           QBQBQBQ                   BBBBB                       | ",
        "                                                                                                                                   | ",
        "                          QBQBQ                   QBQBQ                              QBQBQBQBQ                                    | ",
        "       PP          PP                                       PP          PP                    PP            PP                     | ",
        "  E    PP    S E   PP    E         E        E               PP    E     PP     S   E          PP      E     PP     S               | ",
        "       PP    C C   PP    C C C     C                        PP          PP     C C C           PP            PP    C  C            | ",
        "GGGGGGGPPGGGGGGGGGGPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGPPGGGGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGGGPPGGGGGGGGGGGGGGGGGGGGG",
        "GGGGGGGPPGGGGGGGGGGPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGPPGGGGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGGGPPGGGGGGGGGGGGGGGGGGGGG",
        "GGGGGGGPPGGGGGGGGGGPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGPPGGGGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGGGPPGGGGGGGGGGGGGGGGGGGGG",
    ],
    (1, 2): [
        "                                                                                                                      F",
        "         H                                     H                                     H                                |",
        "                                                                                                                      |",
        "              QBQBQBQ                                     QBQBQBQ                                                     |",
        "                                                                                                                      |",
        "                                  BBBBB                                     BBBBB                                     |",
        "                                                                                                                      |",
        "         E           S           E           M           E           S           E           M                        |",
        "  C C C     C C C       C C C       C C C       C C C       C C C       C C C       C C C       C C C                     |",
        "GGGGGGGGLLLLLLLLGGGGGGGGGGGGGGGGLLLLLLLLGGGGGGGGGGGGGGGGLLLLLLLLGGGGGGGGGGGGGGGGLLLLLLLLGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    ],
    (1, 3): [
        "                                                                                                                      F",
        "                                                                                                                      |",
        "                                                                                                                      |",
        "              QBQBQBQ                                     QBQBQBQ                                                     |",
        "                                                                                                                      |",
        "                                  BBBBB                                     BBBBB                                     |",
        "                                                                                                                      |",
        "         E           S           M           E           S           M           E           S                        |",
        "  C C C     C C C       C C C       C C C       C C C       C C C       C C C       C C C       C C C                     |",
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
        "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    ],
    (1, 4): [
        "                                                                                                                         F      ",
        "                                                                                                                         |      ",
        "                                                                                                                         |      ",
        "      QBQBQBQ                       BBBBBBBBBBB                           QBQBQBQBQ                      BBBBB           |      ",
        "                                                                                                                         |      ",
        "                   BBBBBBBBB                         BBBBBBBBBB                         BBBBBBBBB                        |      ",
        "                                                                                                                         |      ",
        "  R  E    S    R             R   E    S        R                R   E    S         R              R   E    S             |      ",
        "    C C     C C C                    C C      C C C                    C C C             C C C                           |      ",
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    ]
}
